# Generated by Django 2.1.4 on 2019-01-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('landmark', models.CharField(default=None, max_length=50, null=True)),
                ('city', models.CharField(default=None, max_length=50, null=True)),
                ('state', models.CharField(default=None, max_length=20, null=True)),
                ('pin', models.IntegerField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email2', models.EmailField(max_length=60)),
                ('specialist_In', models.CharField(choices=[('Painters', 'Painters'), ('Home decorators', 'Home decorators'), ('Beauty & SPAs', 'Beauty & SPAs'), ('Other small business', 'Other small business')], default='Painters', max_length=50)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('PAN_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=17, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('address', models.ManyToManyField(to='accounts.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserSignup')),
            ],
        ),
        migrations.AddField(
            model_name='artistaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UsersProfile'),
        ),
    ]
